### ISSUE TITLE
General theme color picker will not be fully displayed

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/medico#1]
The color picker pallet will not fully display when we want to change the theme's color :
https://prnt.sc/uxn3ia

**Comment by codepixar** [comment]
Thanks @Florin415 for your query. As we are using the 'Epsilon Framework' & 'Epsilon Dashboard' library with each of our wp themes, the customizer color options and theme options are coming from there. We are just using their library with our theme. So, the bug is coming from there. So, they should update the issue by their end.

Thanks
