### ISSUE TITLE
Header color pallet not fully showing

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/medico#2]
The color pallets for the header's following options do not fully appear :
Header right button text color : https://prnt.sc/uxn5tx
Header right button bg color : https://prnt.sc/uxn60b

**Comment by codepixar** [comment]
Thanks @Florin415 for your query. As we are using the 'Epsilon Framework' & 'Epsilon Dashboard' library with each of our wp themes, the customizer color options and theme options are coming from there. We are just using their library with our theme. So, the bug is coming from there. So, they should update the issue by their end.

Thanks
