### ISSUE TITLE
404 page color pallets not fully showing

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/medico#6]
The color pallets for the 404 pages do not fully display  :
404 Text 1  : https://prnt.sc/uxrrk1
404 Text 2 : https://prnt.sc/uxrrry
404 Page Background Color : https://prnt.sc/uxrs05

**Comment by codepixar** [comment]
Thanks @Florin415 for your query. As we are using the 'Epsilon Framework' & 'Epsilon Dashboard' library with each of our wp themes, the customizer color options and theme options are coming from there. We are just using their library with our theme. So, the bug is coming from there. So, they should update the issue by their end.

Thanks
